### ISSUE TITLE
AA Solidified Experience

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#1020]
**Problem**:
Solidified Experience is very rare compared to single player environment.

**How to reproduce/test:**
1.  Create a sword with looting 3 (not required but makes it easier)
2. Spawn or find closest zombie.
3. Kill said zombie. 

**Version:**
-     Minecraft: 1.10.2
-     SpongeAPI: 6.0.0-SNAPSHOT-f247c80
-     SpongeForge: 1.10.2-2107-6.0.0-BETA-1860
-     Minecraft Forge: 12.18.2.2107

**Comment by ProsperCraft** [comment]
Update and try again, some drops were fixed in newer versions, mostly enderio broken spawners.

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.

**Comment by axieum** [comment]
@Zidane @ProsperCraft

This issue is still present on our recently updated HermitPack server (1.5.1; although was still an issue during 1.4.*). Solidified Experience does not appear to be a drop. We have, however, seen bat wings drop (which are another drop from the mod).

Versions:

> Forge: 1.10.2-12.18.3.2185-universal
> SpongeForge: 1.10.2-2171-5.1.0-BETA-1976
> Actually Additions: 1.10.2-r88
