### ISSUE TITLE
Redstone, Redstone Blocks & Ender Eyes unable to be dropped

### ISSUE THREAD

**Issue by trabpukcip** [SpongePowered/SpongeForge#1048]
SpongeForge: spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar (also tested with spongeforge-1.10.2-2123-6.0.0-BETA-1878.jar)
Flux Networks Mod: FluxNetworks-1.9.4-1.0.7.jar
Sonar Core Mod (Required): SonarCore-1.9.4-3.1.6.jar

When Flux Networks is installed it requires that Redstone, Redstone Blocks & Ender Eyes be able to be thrown into fire as part of how the mod works.

Sponge interferes with the behaviour and sends the item right back to the player.
This error is logged in the console as well:
`[Server thread/ERROR] [Sponge]: No entity type is registered for class sonar.flux.common.entity.EntityFireItem`

As a side effect of this if Botania (tested with Botania r1.9-335.jar) is also installed as part of a modpack, it causes a dupe bug when attempting to do redstone to glowstone alchemy, if you manage to get away from the redstone quickly enough it slowly does the alchemy, to... infinity it seemed (or until the mana pool goes dry).

Also tested was not having Flux Networks installed in case Sonar Core was doing something funky, but there was no issue.

Perhaps useful Github code links:
https://github.com/SonarSonic/Flux-Networks/blob/master/src/main/java/sonar/flux/common/entity/EntityFireItem.java
https://github.com/SonarSonic/Flux-Networks/blob/master/src/main/java/sonar/flux/FluxEvents.java#L74

Mod links:
https://minecraft.curseforge.com/projects/flux-networks/files
https://minecraft.curseforge.com/projects/sonar-core/files
https://minecraft.curseforge.com/projects/botania/files

**Comment by trabpukcip** [comment]
The drops issue is worse than what I thought it was.
If you have a stack of one of the 3 offending items and spam shift+q (i.e. drop a stack) you will overflow your inventory with dupes in under 2 seconds with whatever it was and swill keep dropping more into the world.

The dupe issue is not actually related to Botania at all, only the mana pool big slowdown (and going untilk the mana runs out).

**Comment by bloodmc** [comment]
@trabpukcip dupe issue should be fixed in 1914+. Retest.

**Comment by trabpukcip** [comment]
@bloodmc I setup build 1914 on a test server with just SonarCore and Flux Networks installed.
It is still duping and the items can not be dropped.
It was harder to dupe on drop but still very doable.
No log messages of note.

Interestingly on the full mod pack it crashes the client, I could post the log but I don't see how it would be relevant if the underlying issue is still there in an isolated environment.

**Comment by bloodmc** [comment]
@trabpukcip Does this occur with SF 1971?

**Comment by jasoninsane** [comment]
hello! yes the dupe is still there along with not being able to drop redstone and with just sponge forge mod without plugins

**Comment by trabpukcip** [comment]
Sorry about the delay but yeah, still duping, updated forge to the required 2171 build and tested spongeforge builds 1971 and 1980. No changes to Flux Networks or SonarCore.

Here is a quick demo video:
https://youtu.be/goAOwRYsSTY

**Comment by SonarSonic** [comment]
Should be fixed in next update

**Comment by Unnoen** [comment]
@SonarSonic The update does indeed fix the redstone returning to the user, but does not fix the duping of it.

**Comment by KingDan27** [comment]
can confirm this issue happens on Skyfactory3 SF 2202

**Comment by thomas15v** [comment]
Same issue here, we tried to ban the dropping of redstone with stackban. The event gets canceled correctly but the dupe keeps happening.

**Comment by phit** [comment]
yup, tried to prevent it with GP no luck either
https://phit.link/s/2017-01-13_18-31-03.mp4
