### ISSUE TITLE
TPS drop with build 2117

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1253]
After some time server drop tps. When revert to build 2113, issue is resolved and never returned.

https://timings.aikar.co/?id=606fbc9959d74cb692001d0c91a53e39

**Comment by bloodmc** [comment]
2117+ now allows mods to load chunks when calling getTileEntity. Remove Sponge and check if timings are the same, if so then report the issue to the mod dev. If not, zip your world + mods + config so I can fix it.

**Comment by bloodmc** [comment]
http://imgur.com/a/3n50W

As you can see the same issues happen on pure forge with standard redstone conduit setup. Are you using redstone conduits? If so you will need to remove them or prevent players from creating fast clocks.

**Comment by ghost** [comment]
TPS drop started when player disconnects. Looks like chunks remains loaded. Yes use redstone conduits. I will stay on build 2113 it not have this issue.

another timing report: https://timings.aikar.co/?id=ae4f3b583ec74c42b078d1085110455f#505_2

**Comment by bloodmc** [comment]
@hunter688 You need to zip your world so I can test it on my end. Also provide some warmroast screenshots.

**Comment by ghost** [comment]
I can give you live access to warmroast.

![warmroast1](https://cloud.githubusercontent.com/assets/1410134/22882792/2c9193aa-f1ed-11e6-9b39-8dee3e928284.png)

**Comment by bloodmc** [comment]
@hunter688 This has been fixed and will be pushed with my next round of updates.

**Comment by ghost** [comment]
great!

**Comment by ghost** [comment]
Issue still here:

https://timings.aikar.co/?id=cb889664e6d74eef94011295ab57a434

**Comment by bloodmc** [comment]
Upload your world

**Comment by ghost** [comment]
With build 2169 is tps very low, only 4. It is worse than previous test.

https://timings.aikar.co/?id=44a488d7ec1641afa1bb60dc19d87587

world: http://62.182.234.26/world-ic2.tar.gz
modpack: https://www.mirc.cz/ic1102.tar.gz

when tp to 784 78 1109, then somewhere away or log off - conduits starts lag, build 2113 is the latest without this issue.

**Comment by bloodmc** [comment]
@hunter688 I just tested your world and cannot reproduce the issue. I get under 1ms when I log off.

[11:14:40] [Server thread/INFO]: World [world] (DIM0) TPS: 20.000, Mean: 0.771ms
[11:14:40] [Server thread/INFO]: World [DIM-1] (DIM-1) TPS: 20.000, Mean: 0.035ms
[11:14:40] [Server thread/INFO]: World [DIM1] (DIM1) TPS: 20.000, Mean: 0.027ms
[11:14:40] [Server thread/INFO]: Overall TPS: 20.000, Mean: 0.941ms

This is 30 seconds or so after I log off.

These are the timings while logged into 784 78 1109

https://timings.aikar.co/?id=10a73bf58e1f48c7a81ef92a474cb942

**Comment by ghost** [comment]
looks like problem solved (build 2185):

https://timings.aikar.co/?id=7ae53b88988d4fc0ae28ecaf0111ce76

I will make some other tests, then report...

**Comment by ghost** [comment]
Hmm, again :-( 

https://timings.aikar.co/?id=e6f9e3ebbd17499fb39bca149b2aa4b2

**Comment by ghost** [comment]
Latest tests points to enderio block conduits - when neighbor activate only part of conduit network, this leads to tps drop. Network had 853 conduits. This network now cause lag with build 2113 too. I think issue can be closed. Thanks for help.
