### ISSUE TITLE
Something blocking entityAttackEvent

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1256]
In our mod we suscribe to the following event:

    @SubscribeEvent
    public void on(final AttackEntityEvent event)
    { }

It works great without Sponge to cancel that event under certain circumstances but with sponge it doesn't seem to work.

**Comment by Raycoms** [comment]
I was debugging the event, the event does not even get called!

**Comment by Aaron1011** [comment]
What version of Sponge are you running?

**Comment by Raycoms** [comment]
spongeforge-1.10.2-2202-5.1.0-BETA-2034.jar

**Comment by Raycoms** [comment]
Tried it with the newer: 5.1.0-BETA-2100 as well. No difference

**Comment by Aaron1011** [comment]
@Raycoms: This should be fixed in the latest SpongeForge now: https://github.com/SpongePowered/SpongeForge/commit/7c41975c8fd890329a28036f2327898b20a92fc8

**Comment by Raycoms** [comment]
Not fixed. I just tried it out with the newest spongeforge-1.10.2-2221-5.1.0-BETA-2128.jar
Still not working.

**Comment by Aaron1011** [comment]
@Raycoms: Oops - that commit didn't get built on Jenkins for some reason. A new build should be out shortly.

**Comment by Aaron1011** [comment]
@Raycoms: Check now.

**Comment by Raycoms** [comment]
Where do I find them? it's the 2128?

**Comment by Aaron1011** [comment]
files.mionecraftforge.net/spongepowered doesn't seem to have updated its index. You can use [Sponge's download page](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2) to get the latest build.

**Comment by Raycoms** [comment]
Worked
