### ISSUE TITLE
Sponge tracker going crazy

### ISSUE THREAD

**Issue by TheoKah** [SpongePowered/SpongeForge#1298]
Modpack: Direwolf20 1.5.1
Sponge: spongeforge-1.10.2-2221-5.2.0-BETA-2198

This block is spammed and server freeze:
http://pastebin.com/nkgGiMbE

I rollbacked to the version I was on before the update (spongeforge-1.10.2-2221-5.1.0-BETA-2185.jar) and problem not here anymore

Here is a timing report (with 2185, so non-buggy), so you can check the config if needed: https://timings.aikar.co/?id=a54f983bbb754bf0bb58af6674dbe432

**Comment by Aaron1011** [comment]
Can you upload your full `fml-server-latest.log`?

**Comment by Aaron1011** [comment]
Can you re-test on the latest SpongeForge? I've [fixed a bug](https://github.com/SpongePowered/SpongeCommon/commit/ba3642a3d8d086c270d60ad7892c8407587e8ce8) which cause causing chunk loading (and therefore CauseTracker phase completion) to happen off of the main thread.

**Comment by Aaron1011** [comment]
Closing, as I'm almost certain this was fixed in that commit. Please re--open if the issue re-occurs.

**Comment by leelawd** [comment]
I just tested this fix and it is still happening unfortunately.

Here is a full server log.
https://drive.google.com/file/d/0B5kVUsw24he0amJSY0QzOHJwLW8/view?usp=sharing

This is a major issue as within 3 hours of run time, this file became 25GB in size.

**Comment by phit** [comment]
can confirm filled my servers harddrive pretty quick using 2203

**Comment by merjilin** [comment]
sadly, Issue is still occurring when using build 2208 as well.
Here's the fml log which contains the errors: https://drive.google.com/drive/folders/0B-_XApo04kgXVTM5Ty1HS2VOUHc
(ignore the nucleus mixins errors, they're mod conflicts)

**Comment by Aaron1011** [comment]
This should be fixed in [the latest SpongeForge](https://github.com/SpongePowered/SpongeForge/commit/5e4abf30d7db9a344a25a91c69d02018f9d51d4c).
