### ISSUE TITLE
Dragons not spawning with RFTools DIMs

### ISSUE THREAD

**Issue by KingDan27** [SpongePowered/SpongeForge#1384]
Running SF-2241 on FTB Beyond and SkyFactory3 Dragons do not spawn.
Tests completed:
Beyond/Skyfactory3 SF-2241 w/ plugins - no dragons spawn
Beyond/Skyfactory3 SF-2241 w/o plugins - no dragons spawn
Beyond/Skyfactory3 w/o SF-2241 - dragons spawn

Here is the FML Log i could find related to the dimension:
http://pastebin.com/ADZDnyy7

**Comment by bloodmc** [comment]
This should be fixed in latest builds, update.

**Comment by meza** [comment]
This is back in 1.10.2-2281-5.2.0-BETA-2274 :(

[fml-server-latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/956836/fml-server-latest.log.txt)

I went in the dimension, no dragons spawn.
Summoned one with 0 health: no portal spawned.
Summoned one with 1 health and killed it: no portal spawned.

**Comment by phit** [comment]
still an issue with

spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
mcjtylib-1.12-2.5.0.jar
rftools-1.12-7.14.jar
rftoolsdim-1.12-5.05.jar

**Comment by phit** [comment]
seems to be fixed
![](https://i.imgur.com/4nMIsxj.png)

spongeforge-1.12.2-2768-7.1.6-RC3586.jar
rftools-1.12-7.61.jar
rftoolsdim-1.12-5.64.jar
mcjtylib-1.12-3.1.1.jar
