### ISSUE TITLE
InventoryLens issues with Refined Storage

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1775]
- SpongeForge version: spongeforge-1.12.1-2480-7.0.0-BETA-2640.jar
- Forge version: forge-1.12.1-14.22.1.2478-universal.jar
- Mod affected: refinedstorage-1.5.18.jar

User was doing something with the pattern grid from Refined Storage when this crashed, if reproduction is needed let me know and I'll make a step by step.

@Faithcaio 

https://gist.github.com/phit/5e729c0acbba1965cc8d3a2ba336acd1

**Comment by ghost** [comment]
I have similar issue.

**Comment by Sanquira** [comment]
I tested it a little bit and found repro:

Open Pattern grid block and set it to create crafting recipe. Then close and open this blocks GUI. (Now you have initial conditions.) Then switch to processing and WITHOUT closing GUI try paste anything into result grid (i tried middle position). Result is crash.

You are welcome.

**Comment by Faithcaio** [comment]
I think this is caused by the mod changing the container-slots again after creation of the container.
We currently have no way to detect this

**Comment by ghost** [comment]
Will be possible eliminate crash? For example exlude inventory handling for specific block/tileentity in the sponge config etc. as workaround now.

**Comment by phit** [comment]
resolved in 2678

**Comment by phit** [comment]
nvm, rightclicking a stack in the grid still crashes

https://gist.github.com/phit/6be8a8e99a2df8f527e6a8cb2c71cf0b

**Comment by Faithcaio** [comment]
Problem not fixed but this should now no longer crash the server with latest.

**Comment by phit** [comment]
solved in https://github.com/SpongePowered/SpongeCommon/commit/f1d4b40ab2319f8bd83bdcb7fa9f3c4d51d0771d
