### ISSUE TITLE
A bug with blocks from mods. Substitution of block identifiers.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#1886]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2757
- Forge version: 14.23.1.2555
- Java version: Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: Ubuntu Server 16.04

Plugins (18): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, CmdCalendar, CommandUtils, EasyScoreboards, EconomyLite, GriefPrevention, JobsLite, LangSwitch, LuckPerms, Nucleus, PlaceholderAPI, TabManager, UltimateChat, VillagerShops

 Mods (44): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Bed Patch, BetterBedrockGen, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Cavern, CoFH Core, CoFH World, CodeChicken Lib, Deadly Monsters, FastAsyncWorldEdit, Fishing Net Mod, FoamFix, FoamFixCore, Forestry, Giacomo's Foundry, Gravestone Mod, IndustrialCraft 2, Mantle, Multi-Storage, NetherPortalFix, Netherending Ores, QuantumStorage, Reborn Core, Redstone Arsenal, Redstone Flux, ShetiPhian-Core, Tech Reborn, Thermal Dynamics, Thermal Foundation, Tinkers' Construct, Tree Chopper, WorldEdit, mercurius_updater

I can not determine the cause of the error.

[fml-junk-earlystartup.zip](https://github.com/SpongePowered/SpongeForge/files/1526811/fml-junk-earlystartup.zip)

**Comment by ryantheleach** [comment]
Are you talking about the cause tracker spam in the logs? Or is there a bigger problem?

What does "A bug with blocks from mods. Substitution of block identifiers." mean?

**Comment by SawFowl** [comment]
The problem appeared suddenly. Blocks became chaotically replaced with others. For example, blocks of lumber from the Foresty fashion could be turned into ores from the fashion BiomesO'Plenty. All this was accompanied by spam in the console and disconnection of players. I had to make a wipe on the server, since just a rollback of the world did not help, the problem returned. Vip did yesterday, now I see if the problem will appear again.
Sorry for my English. I used google translator.

**Comment by PurpleIsEverything** [comment]
This seems to be a common problem with all 1.12 servers running Sponge the only solution to it currently is to copy a level.dat from a backup of the same world. From the looks of it the registry map is getting damaged or modified when this happens blocks change into other blocks and if the world loads like that then those same blocks can lose NBT data too.

**Comment by SawFowl** [comment]
After I removed the WorldEdit and FastAsyncWorldEdit mods, the blocks stopped changing due to this error, but sometimes I see their disappearance, including vanilla ones. The stability of the server as a whole has grown after this.

**Comment by me4502** [comment]
Does that still occur with just WorldEdit (Not FastAsyncWorldEdit)?

**Comment by SawFowl** [comment]
After I put the WorldEdit plug-in instead of mod, the block changing stopped, but the error in the console was the same as before. 1 time a piece of blocks was missing, but not on such a scale as before.

**Comment by PurpleIsEverything** [comment]
This issue is not related to WE or FAWE multiple servers have had issues without the servers ever having either of those two plugins/mods installed.

**Comment by SawFowl** [comment]
FAWE(Forge) only exacerbated the problem, but was not its cause. FAWE(Forge) does not work correctly with blocks from mods, so the blocks were replaced.

**Comment by PurpleIsEverything** [comment]
Again, this issue occurs with FAWE and WE never being installed.

**Comment by gabizou** [comment]
If someone can zip the level.dat file before and after accompanied with a trimmed down error log that may help to isolate how sponge may be interfering with block substitutions. Otherwise sponge has no code in place that touches block substitutions or the level.dat for the case of block id’s.

**Comment by phit** [comment]
I'm gonna assume this is the same issue me and other server admins have been seeing for a while now. I have yet to find any reproduction, when diffing my level.dat I also never found anything that hinted towards something going wrong there, but @ShadowKitten made different experiences in that regard as in rolling back the level.dat worked for him.

**Comment by PurpleIsEverything** [comment]
Yes, we definitely found resolve on multiple occasions by rolling back the level.dat to one of our hourly snapshots. However this issue is often not replica-table and when it happens it often causes crashes which results in loss of any logs due to the current logging issue where everything is placed in the junk log.

Even when this is not the case more often than not cause-tracker spam which we cannot mute causes these log files to be several gigabytes in size making it impossible to find any errors which may be the result of this bug.

Once this occurs again we will try and keep copies of both a good and bad level.dat though @phit has already found there seems to be no difference where it should matter.

**Comment by SawFowl** [comment]
I saved the level.dat file before and after changing the block ID. As I said before, the replacement of id is observed only if the WorldEdit mode is installed. The plugin does not give this effect, because it does not work with blocks from mods.

[world dat.zip](https://github.com/SpongePowered/SpongeForge/files/1548765/world.dat.zip)

**Comment by phit** [comment]
this was hopefully solved with https://github.com/SpongePowered/SpongeForge/commit/9bf6989675a5559f651e784d82a5f0adc1fbecec

for more information read the announcement https://forums.spongepowered.org/t/psa-spongeforge-rb-2990-spongevanilla-rb-33-for-minecraft-1-12-2/23123

**Comment by Sir-Will** [comment]
@phit the issue is not resolved unfortunately. Running SpongeForge 3002 and it still happens.

**Comment by SawFowl** [comment]
After the fix, I do not notice the problem yet, but I continue to observe.

**Comment by phit** [comment]
that's a shame, if you have any more ideas how to reproduce this please feel free to add that here
same for any logs or other maybe relevant files

**Comment by SawFowl** [comment]
I have no idea what causes this problem. She appears suddenly. If she comes back to me again, I'll let you know right away.

**Comment by Sir-Will** [comment]
So after many days of testing, debugging an so on I finally found out what is causing it.
If you have any sponge plugin which cancels the `UnloadWorldEvent` of the overworld on shutdown then you will have changed block id's.

This bug should be fixed asap.

This is not in issue in the 1.10 sponge version.

**Comment by Mohron** [comment]
That doesn't explain why world edit forge and FAWE forge were found to have some relation to the issue. When I removed them, I stopped having this issue.

**Comment by phit** [comment]
I never had WE or FAWE installed and had this issue happen, nor did I ever have a plugin that cancels `UnloadWorldEvent`,
but for me this issue has been pretty much non existent since I set `deny-chunk-requests=false` which is now default.

At this point I think this whole thing probably has multiple causes that can lead to it.

**Comment by Sir-Will** [comment]
Well, I can reproduce it all the time with just SpongeForge, Forestry and a single class plugin which cancels the unload event while `deny-chunk-requests` is set to false.

**Comment by Zidane** [comment]
@Sir-Will 

I pushed a change to SpongeForge that makes sure to not stop the saving logic on shutdown even if you cancel UnloadWorldEvent.

Generally via normal API methods you can NEVER unload the Overworld and during the server lifecycle it'll never be told to unload UNTIL we're shutting down. This was an oversight (a bad one at that).

I'll close this until another scenario crops up that can be reproduced.
