### ISSUE TITLE
Woot - Unable to Capture Dragon

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1912]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2794
- Forge version: forge-1.12.2-14.23.1.2560-universal
- Java version: 1.8
- Operating System: Ubuntu

- Plugins/Mods:
**Plugins (20):** Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, AutoBroadcaster, BadgeUp Sponge Client, BetterChunkLoader, CarrotShop, DimReseter, Discord Bridge, EconomyLite, GotR Sponge, GriefPrevention, ItemChat, LuckPerms, MMCReboot, NoXray, Nucleus, Serious Coms, SleepVote
**Mods (114):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AbyssalCraft, AbyssalCraft Integration, Actually Additions, Actually Baubles, Advanced Generators, AppleSkin, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Baubley Heart Canisters, Better Advancements, Better Builder's Wands, BiblioCraft, Bookshelf, Botania, Brandon's Core, Carry On, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compact Machines 3, Cooking for Blockheads, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Cucumber, Cyclops Core, Dark Utilities, Draconic Evolution, ET Lunar, EnderTanks, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extra Utilities 2, FTBLib, Farming for Blockheads, FastAsyncWorldEdit, FoamFix, Guide-API, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, Integration Foregoing, Iron Backpacks, JourneyMap, Just Enough Items, Lost Souls, MTLib, Magical Psi, Mantle, Mod Tweaker, Multi-Storage, Mystical Agradditions, Mystical Agriculture, Natura, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, Pam's HarvestCraft, Placebo, PlusTiC, ProjectE, Psi, QuantumStorage, RFTools, RFTools Control, Random Things, Reborn Core, Redstone Arsenal, Redstone Flux, Rocky Core, Sampling Performance Profiler, Shadowfacts' Forgelin, ShetiPhian-Core, Simple Inventory sorting, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tiny Progressions, Tomb Many Graves, TorchMaster, UniDict, Valkyrie Lib, WanionLib, Woot, WorldEdit, XNet, YABBA

**Issue Description**
An Ender Shard is used to capture the essence of a mob by punching it then killing it to fill it. When punching an ender dragon or Wither boss with an Ender Shard on an SF server, it is unable to capture the mob's essence.

**Comment by phit** [comment]
works with woot-1.12.2-1.0.1.jar
Guide-API-1.12-2.1.5-60.jar
on Sponge eed4b540aeff1dd1be8670da969f9c525ddd31dc

**Comment by demon57730** [comment]
I have the same problem

spongeforge-1.12.2-2611-7.1.0-BETA-3004.jar
woot-1.12.2-1.0.1.jar
Guide-API-1.12-2.1.5-60.jar

**Comment by phit** [comment]
did you test with just those 3 mods?

**Comment by demon57730** [comment]
I just do it with another server even forge even the same 3 mod avaritia and more (this mod does not change any mob) and still I can not always capture the dragon with woot

**Comment by phit** [comment]
does the wither work?

**Comment by demon57730** [comment]
it seems to me that yes I will test two minutes because I find another bug but I will see if these forge or sponge that cause it

**Comment by demon57730** [comment]
https://youtu.be/-SFUX2TncLc

in this video I show that I capture the wither but not the dragon ender

at the end I show the server ftp with the 4 mod + forge + sponge

__________________________________________________________________________________________________

in the video you see that I kill in 1 blow with the sword the wither but not possible with the dragon these sword of Avaritia.

Well, I removed the spongeforge mod and I could kill the dragon ender with the sword in one shot and even capture him so he has a problem with the dragon and spongeforge ender

**Comment by phit** [comment]
thanks for testing!

for reference Woot's capture code is [here](https://github.com/Ipsis/Woot/blob/1_12/src/main/java/ipsis/woot/item/ItemEnderShard.java#L57)

**Comment by demon57730** [comment]
so he has a worry with the sword of avarita and the dragon because without spongeforge the sword kills the dragon in 1 shot but with spongeforge the sword is not effective as if spongeforge says that the dragon is not a mob or rather he does not know the dragon ender

**Comment by demon57730** [comment]
[16:53:01] [Server thread/WARN] [net.minecraft.stats.StatisticsManagerServer]: Invalid statistic in ./world/stats/e7e67562-eb9a-4853-881d-8e62e91b3baf.json: Don't know what stat.useItem.woot.endershard is
[16:53:01] [Server thread/WARN] [net.minecraft.stats.StatisticsManagerServer]: Invalid statistic in ./world/stats/e7e67562-eb9a-4853-881d-8e62e91b3baf.json: Don't know what stat.useItem.avaritia.infinity_sword is
[16:53:01] [Server thread/WARN] [net.minecraft.stats.StatisticsManagerServer]: Invalid statistic in ./world/stats/e7e67562-eb9a-4853-881d-8e62e91b3baf.json: Don't know what stat.useItem.avaritia.infinity_pickaxe is
[16:53:01] [Server thread/DEBUG] [mixin]: Mixing advancement.MixinPlayerAdvancements from mixins.common.core.json into net.minecraft.advancements.PlayerAdvancements

**Comment by phit** [comment]
please don't fill this issue with unrelated things, open a separate issue for the avaritia stuff

**Comment by Aang23** [comment]
Got the exact same issue here, using both the recommended build or the latest.
It's also impossible to capture Draconic Evolution's Chaos Guardian. It works without sponge.

**Comment by demon57730** [comment]
I put the last recommended version of forge with sponge a day so it does the same thing

**Comment by gabizou** [comment]
This should be resolved once #2110 is completed and merged.

**Comment by JoeSGT** [comment]
@gabizou  this issue is still not fix in SpongeForge 7.1.0-BETA-3136 in fact it don't even say capture mob in chat when attempting to capture the ender dragon. When i attempt to capture the ender dragon in singleplayer it works just fine without SpongeForge.

**Comment by Whazaaaaa** [comment]
Would like to also add that its still not working.

woot-1.12.2-1.2.1
Guide-API-1.12-2.1.5-60
forge-1.12.2-14.23.4.2705-universal
spongeforge-1.12.2-2705-7.1.0-BETA-3148

If more tests are needed to be done, I would be happy to do them.

**Comment by Wissi** [comment]
Also adding our server to the list of still not working. Neither the Wither nor the Ender Dragon.

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3401
- Forge version: 1.12.2 - 14.23.4.2705
- woot-1.12.2-1.4.2
- Guide-API-1.12-2.1.7-62
- Java version: 1.8.0_181

**Comment by jinkhya** [comment]
Hello, as I was looking if that issue was a sponge issue, found this thread. 
It seems to be the same on : 
spongeforge-1.12.2-2705-7.1.0-BETA-3477.jar
forge 2760
woot-1.12.2-1.4.4.jar
Guide-API-1.12-2.1.6-61.jar

Thanks in advance.

**Comment by Shybella** [comment]
This is still a issue to this day, one year later. 

I can confirm this is still a problem with 1.12.2-2768-7.1.5-RC3511 Spongeforge + woot woot-1.12.2-1.4.7

**Comment by LemADEC** [comment]
As of forge-1.12.2-14.23.5.2811, spongeforge-1.12.2-2768-7.1.6-RC3565 and woot-1.12.2-1.4.9 in a large kitchensink modpack, only Ender dragon can't be programmed.
Other bosses works fine, including Wither, Evoker, Elder guardian, Thaumcraft Eldritch construct, Nex Ghast mother and Twilight Forest hydra.

**Comment by ImMorpheus** [comment]
This is strange. I was pretty sure this was fixed with the Interact events PR.

I'll look into it.

Edit: yeah, the EnderDragon was a separate issue.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/420167c84ec7fe564b9e96a6817f6c79dd55fa32

**Comment by H3roDude** [comment]
Got that issue with Version: spongeforge-1.12.2-2768-7.1.5 | woot-1.12.2-1.4.10 |

**Comment by gabizou** [comment]
@H3roDude You'll need to use a newer version of SF that has the commit, Specifically 1.12.2-2768-7.1.6-RC3586 will have the commit listed above. Though, there are significant updates in newer builds since then.

**Comment by H3roDude** [comment]
Okay last time i used a 7.1.6 version kinda everything was bugged out so i backported it. Will give it a try
