### ISSUE TITLE
Advanced Rockety Item causing Duplication glitch with sponge

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1957]
**I am currently running**

- SpongeForge version:  1.12.2-2555-7.1.0-BETA-2834
- Forge version:  1.12.2-14.23.1.2581
- Java version:  8
- Operating System: Linux

- Plugins/Mods:
Just having AdvancedRocketry and
LibVulpes Version - 1.12.2-0.2.7-25
griefprevention-1.12.2-4.3.0.511
LuckyPerms - 4.0.46

**Issue Description**
Advanced rockerty have this item called `Basic Laser Gun` it is an item that you can shoot laser to mine stuff the item work well with sponge until i had found this issue when someone attempt to create a claim using GriefPrevention and you yourself do not have access to the claim and attempt to shoot the laser about 5-6 blocks away and it drops the block without the block breaking
the mod developer has also pointed this out 
https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/item/tools/ItemBasicLaserGun.java#L225

more about what the mod developers had said can be found here 
https://github.com/zmaster587/AdvancedRocketry/issues/1064

**Comment by gabizou** [comment]
(I'll be replying to both issues on sponge and here)
I have a feeling that I'll need to port over the same sort of workaround fixes for Sponge's entity drop captures to work with block drop captures, similar to the [in development branch handling entity drop captures automatically with sponge's tracking system](https://github.com/SpongePowered/SpongeForge/compare/stable-7...refactor/entity-drop-compatibility?expand=1) to resolve the [hatchery issue with sponge itself](https://github.com/SpongePowered/SpongeForge/issues/1259). I'll be working on the fixes and testing against AR and Hatchery to verify issues are resolved and report back here.

**Comment by bloodmc** [comment]
Unable to replicate this issue with latest SF and GP. Retest with a CLEAN server and ONLY GP/SF/LP/Advanced Rocketry. Make sure everything is updated to latest.

**Comment by JoeSGT** [comment]
It seem that it's fixed it's possibly got fixed by the new GP update because with SF i had 
spongeforge-1.12.2-2555-8.0.0-BETA-2841 and i was able to do it 
but i updated GP/SF/LP and it work thanks @bloodmc

**Comment by ryantheleach** [comment]
I wonder what fixed it...

@JoeSGT For the record you shouldn't be using 8.0.0 builds of SpongeForge unless you are developing / assisting in the development of Sponge API for 1.13 Things might be working now, but they will very quickly diverge once we have 1.13 snapshot support or a 1.13 MCP project to play with.

**Comment by ryantheleach** [comment]
Reopened by request of blood, he believes there is a deeper issue still existing in Sponge.

**Comment by gabizou** [comment]
Yeah. I was going to say that this issue is more about the capture syncing that has to take place

**Comment by gabizou** [comment]
@phit so this issue is currently fixed with the branch?

**Comment by phit** [comment]
@gabizou what was the issue even?
>It seem that it's fixed it's possibly got fixed by the new GP update because with SF i had

[its not even an issue on the current stable anymore](https://github.com/zmaster587/AdvancedRocketry/issues/1064#issuecomment-359340402) and is only open, as ryan said, due to blood requesting it

**Comment by gabizou** [comment]
I'll keep it closed then as I couldn't thread through to find the issue relevant in my branch anymore.
