### ISSUE TITLE
Chunk Loading not working aroma1997 mining dimension while online.

### ISSUE THREAD

**Issue by WiffleBen** [SpongePowered/SpongeForge#2203]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3136
     -The latest version of spounge forge doesn't allow players to place water or lava out of buckets, strange bug.
- Forge version: forge-1.12.2-14.23.4.2705
- Java version: build 1.8.0_171-b11
- Operating System: Windows 10 Pro

- Plugins/Mods:Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Advanced Rocketry, Advanced Rocketry Core, Advanced Solar Panels, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, BetterBedrockGen, BetterChunkLoader Forge Lib, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, Flat Colored Blocks, FoamFix, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, GravityGun, Hats, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JourneyMap, Long Fall Boots, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mekanism, MekanismGenerators, MekanismTools, Mercurius, MineTogether, MineTogetherServer, Mod Support, Mod Tweaker, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, UniDict, Valkyrie Lib, Vein Miner, Vulpes library, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library/ Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActiveTime, BetterChunkLoader, LuckPerms, Nucleus, Total Economy, Web-API, WorldEdit

**Issue Description**
Okay, so I've done a good deal of troubleshooting to ensure that it was in fact that sponge-forge that was causing the problem. So it seems it doesn't matter the version of sponge or forge, chunk loading does not work. I discovered this first when I was using a digital Miner from mekanism, I would teleport away from the miner that had a chunk loader upgrade on it and the enderchest would just not fill up as if the chunk wasn't loaded and the miner couldn't work because of it. I tried Chicken Chunks chunk loaders with a radius that encompased the entire range of the miner and still this did not work, every time I teleport away just chunk just unloads. I then tried this with RFTools builder with the quarry upgrade and an enderchest that is linked between it and my base. The enderchest would not empty when I was in the mining dimension and the quarry would not run when I was out of it. I uninstalled sponge and tested this and chunks were loading fine, The error is just when I teleport from the overworld to this dimension the chunks do not stay loaded. It's also important to note that if I am offline the chunks are loaded as the chunk loader I am using for each of these items load offline. This is really strange and sort of mind boggling. If I did not explain this well I am sorry, I'm just trying to report this so hopefully It can be fixed.
 The server didn't crash.

**Comment by phit** [comment]
upgrade to latest this was fixed in 7.1.0-BETA-3144

**Comment by WiffleBen** [comment]
this was still happening in the latest version
meaning 7.1.0-BETA-3146 as of now
I will test with the release that came out 6 hours ago though
Working with the latest release

**Comment by WiffleBen** [comment]
meaning 7.1.0-BETA-3146 as of now

**Comment by WiffleBen** [comment]
I will test with the release that came out 6 hours ago though
