### ISSUE TITLE
Server/Client crash with Mystcraft

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2213]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3151
- Forge version: 1.12.2-14.23.4.2707
- Java version: 1.8.0_162 & 1.8.0_171
- Operating System: Windows 10 & CentOS

- Plugins/Mods:
mystcraft-1.12.2-0.13.4.03
no other mods
no plugins

**Issue Description**
Server crashes when starting/loading a new world in single or multiplayer.
```
Stacktrace:
	at net.minecraft.world.WorldServer.setActiveConfig(WorldServer.java:1839)
	at net.minecraft.world.gen.ChunkProviderServer.handler$onConstruct$zme000(ChunkProviderServer.java:601)
	at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:45)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy$ChunkProviderServerDummy.<init>(WorldProviderMystDummy.java:64)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.replaceChunkProvider(WorldProviderMystDummy.java:289)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.calculateInitialWeather(WorldProviderMystDummy.java:282)
	at net.minecraft.world.World.func_72947_a(World.java:2543)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:122)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:791)
	at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:619)
	at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:561)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:748)
```

https://gist.github.com/LemADEC/7d74c2f8614562e46aaa33834eabc214

**Comment by gabizou** [comment]
Should be fixed with https://github.com/SpongePowered/SpongeForge/commit/22ec41cc1d7153f0ba6d36ca2c46b601e5d9fe44

SpongeForge 3163 should have the fixes and avoid the crash.

**Comment by LemADEC** [comment]
Issue is still reproduced with spongeforge-1.12.2-2705-7.1.0-BETA-3163.jar:
```
[20:06:05] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@235ce65:
java.lang.NullPointerException: null
>       at net.minecraft.world.WorldServer.setActiveConfig(WorldServer.java:1839) ~[oo.class:?]
>       at net.minecraft.world.gen.ChunkProviderServer.handler$onConstruct$zme000(ChunkProviderServer.java:606) ~[on.class:?]
>       at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:45) ~[on.class:?]
>       at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy$ChunkProviderServerDummy.<init>(WorldProviderMystDummy.java:64) ~[WorldProviderMystDummy$ChunkProviderServerDummy.class:?]
>       at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.replaceChunkProvider(WorldProviderMystDummy.java:289) ~[WorldProviderMystDummy.class:?]
>       at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.calculateInitialWeather(WorldProviderMystDummy.java:282) ~[WorldProviderMystDummy.class:?]
>       at net.minecraft.world.World.func_72947_a(World.java:2543) ~[amu.class:?]
>       at net.minecraft.world.WorldServer.<init>(WorldServer.java:122) ~[oo.class:?]
>       at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:791) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3163]
>       at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:619) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3163]
>       at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:561) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3163]
>       at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:748) ~[DimensionManager.class:?]
>       at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:4146) ~[MinecraftServer.class:?]
>       at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:353) ~[InstabilityDataCalculator.class:?]
>       at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:188) ~[InstabilityDataCalculator.class:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_950_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) [EventBus.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590) [EventBus.class:?]
>       at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265) [FMLCommonHandler.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Aaron1011** [comment]
There are two issues here. The first is relatively simple: `WorldServer#setActiveConfig` ends up being called from the `WorldServer` constructor, before the `mixinChunkProviderServer` field is initialized. Since Mystcraft directly modifies the `chunkProvider` field, we should simply get rid of `mixinChunkProviderServer`.

The second issue is that Mystcraft's dummy WorldInfo has a null `levelName`. The simplest solution would probably be to create a dummy `SpongeConfig` object for such a world, which is never actually saved to disk.

**Comment by NEXUS2345** [comment]
I can also reproduce this issue on SpongeForge 7.1.0 BETA 3238. Is there any status update on this issue?

**Comment by Zidane** [comment]
@Aaron1011 

A better fix (and a longer drawn out one) is simply to not touch any "fake" worlds. Even at the config level.

**Comment by Aaron1011** [comment]
@Zidane: I've gotten the world to load on this branch: https://github.com/SpongePowered/SpongeCommon/tree/fix/mystcraft-issues

However, I'm going to take a closer look at how we handle 'fake' worlds.

**Comment by phit** [comment]
@Aaron1011 status on this? 
just got another report for this on discord https://gist.github.com/phit/9a30d26c65377fe96d937ed3567aff1d

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge
