### ISSUE TITLE
GUI gets forced closed when sneak-right clicking RF Tools Network Monitor Item on a Tile Entity

### ISSUE THREAD

**Issue by Fatmice** [SpongePowered/SpongeForge#2248]
**I am currently running**

[07:52:03] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-d453c3e
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3204
    Minecraft Forge: 14.23.4.2705
Server: Linux 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64
Client: Windows 10

- Plugins/Mods:
> sponge plugins
[07:51:36] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge
> sponge mods
[07:51:39] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Mods (125): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AbyssalCraft, Advanced Generators, Applied Energistics 2, Astral Sorcery, BD Lib, Baubles, BiblioCraft, Biomes O' Plenty, Black Hole Storage, Bonsai Trees, Bookshelf, Brandon's Core, CC: Tweaked, CLibrary, Calculator, Chameleon, Charset, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compacter, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Defier, Doomlike Dungeons, Draconic Evolution, ET Lunar, Elevator Mod, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Flux Networks, Guide-API, Guidebook, Hammer Core, Immersive Engineering, Immersive Petroleum, Immersive Tech, In-Game wiki Mod, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Inventory Tweaks, JourneyMap, Just Enough Items, LagGoggles, MCMultiPart, MatterOverdrive, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, Nature's Compass, Not Enough Items, NuclearCraft, OMLib, Open Modular Turrets, OpenComputers, OpenComputers (Core), OpenComputers Sensors, OpenComputers Xnet Driver, Practical Logistics 2, Pressure Pipes, ProjectE, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, Reborn Core, Redstone Flux, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Sampling Performance Profiler, SonarCore, Storage Drawers, Tech Reborn, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Equivalence, The One Probe, The Twilight Forest, Thermal Expansion, Thermal Foundation, TickProfiler, UniDict, Universal Modifiers, Valkyrie Compat, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, Woot, XNet, p455w0rd's Library

**Issue Description**
Per description.  I've been having this issue for a long time.  I was hoping it would go away with newer version of SpongeForge but it has not.  The RF Tool Network Monitor Item can be sneak-right clicked on a cable to get GUI that reports the rate of energy transfer in the network to which that cable belonged.  In single player, this worked without issues.  In multiplayer running SpongeForge, the GUI will open then immediately closed.  It will stay open when sneak-right clicked or just right clicked on a block, like gold block.

I've reported this issue to mod author but seems not much can be done on their end as they deemed it a Spongeforge issue.
https://github.com/McJtyMods/RFTools/issues/1446
https://github.com/McJtyMods/RFTools/issues/1448

https://gist.github.com/Fatmice/350cd19735c66fc1b9471ac21987058f

**Comment by Fatmice** [comment]
I've updated to newest beta
spongeforge-1.12.2-2705-7.1.0-BETA-3218.jar

Problem seems to have gone away but now the commands /sponge plugins or /sponge mods or anything /sponge have disappeared

**Comment by phit** [comment]
closing, as it was solved. for the command issue follow https://github.com/SpongePowered/SpongeCommon/issues/1953

**Comment by Fatmice** [comment]
@phit please reopen.  I just found that it is not solved.  SpongeForge 3221 did not load due to conflict with LagGoggles' Mixin, so it made it seemed as if the problem went away.  It did not.

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge.
