### ISSUE TITLE
EnderIO Dark Steel Armor

### ISSUE THREAD

**Issue by batteryhun78** [SpongePowered/SpongeForge#2320]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3320 or any version
- Forge version: 14.23.4.2732
- Java version:  Version 8 Update 171
- Operating System: Win10 or Linux

- Plugins/Mods:
Direwolf20 2.1.0 all the mods, but tested with only EnderCore, EnderIO, Sponge present, and without Sponge. Without Sponge, everything is fine. I'm sure it's between the two mods.

**Issue Description**
https://github.com/SleepyTrousers/EnderIO/issues/4782

---

> Issue Description:
> 1.12.2-5.0.29 version of EnderIO, and any Version of Sponge Forge (I did test older) makes this problem, where essentially after putting the "Sponge Forge" "mod" into the mods folder in the server, loading it, does this problem [Tested on Direwolf 2.1.0 Server]. What's the problem exactly? EnderIO Armors, so Dark Armor and the Ender Armor With my words, it looks like, something happening with the "absorbtion" where if it's empowered and fully charged, you less likely to get damage from mobs because of the absorbtion when your suit is powered, as it is written. When the two "mods" are present, something happens with these armors, and I got no protection at all. As I tested, Zombies does the same damage as if I did not wear anything. I have already asked this on Sponge [First Link] but we did not get a definite conclusion. --> [Second Link] <--- This is the log, and the debug file, from my test server, where the two "mods" were together and where the problem occured. [Direwolf20 1.12, 2.1.0]
> 
> I tested, what if I delete all the other mods.
> |1| Only EnderIO [EnderIO-1.12.2-5.0.29] and EnderCore EnderCore-1.12.2-0.5.35 Without Sponge--> Works
> |2| EnderIO [EnderIO-1.12.2-5.0.29], EnderCore [EnderCore-1.12.2-0.5.35] and Sponge [spongeforge-1.12.2-2705-7.1.0-BETA-3320] With Sponge --> Doesn't work [Third link] Contains debug and log file
> 
> What happens:
> Something with the "damage" absorbtion
> 
> What you expected to happen:
> that the armor works the way it should be, and as it is written.
> Steps to reproduce:
> Put any SpongeForge version into the mods folder
> Start the Server
> Test if the absorbtion works when the armor is powered. Without Sponge--> Works | With Sponge --> Doesn't work
> ...
> Affected Versions (Do not use "latest"):
> EnderIO: EnderIO-1.12.2-5.0.29
> EnderCore: EnderCore-1.12.2-0.5.35
> Minecraft: 1.12
> Forge: 14.23.4.2732
> Sponge: spongeforge-1.12.2-2705-7.1.0-BETA-3320, 3307 - but looks like any version of Sponge will create the same issue.
> Your most recent log file where the issue was present:
> |1| https://imgur.com/a/s8q9hBw
> |2| https://drive.google.com/open?id=1XQTjknLIC9bIA2A26-F2fFAmSlQyUQsX
> |3| https://drive.google.com/open?id=1nzyNU40OX5H2QTdtKCy6nNl6W8ds1ZFf

---

|1| https://imgur.com/a/s8q9hBw
|2| https://drive.google.com/open?id=1XQTjknLIC9bIA2A26-F2fFAmSlQyUQsX
|3| https://drive.google.com/open?id=1nzyNU40OX5H2QTdtKCy6nNl6W8ds1ZFf

**Comment by tyler489** [comment]
Is related to issue #1192

**Comment by gabizou** [comment]
Because there's a lot of confusion going around, can I get a very precise explanation on how to reproduce the issue? What steps, what items *specifically* and how to test the items work without sponge forge?

**Comment by tyler489** [comment]
Place down any tier of energy or fluid conduit from enderio. Then get a different tier of energy conduit or fluid conduit and place it down. The first conduit should disapear and the one you placed should go down in stacksize... in vanilla forge it does... in spongeforge it doesnt

**Comment by tyler489** [comment]
Sorry i misread the issue. i thought this was a different issue... which was  not reported yet and as such i just opened a new issue for it (#2325)

I have removed my confusing statements from this thread
This was origionally reported as https://github.com/SleepyTrousers/EnderIO/issues/4782
on enderio's github

**Comment by batteryhun78** [comment]
@gabizou Simply, get a simple server. I used Direwolf 2.1.0. Without sponge forge[any version] the modpack-EnderIO works fine. But I need some plugins to my server, so let's put the sponge forge into the mod folder, where it should be. After this act, I was wearing my armor from EnderIO and realized that it doesn't "work" because i take two heart damage from skeleton, one and a half from zombie, it looked like the "apsorbtion" didn't work((The suit was "empowered")), but after removing sponge forge, everything was fine.

Currently there's two armor type from EnderIO, the Dark one, and the Ender one. - Both does the same when I take damage and sponge forge is in present. If I fall into the lava, with wearing the suit. I'm instantly dead, like I wasn't wearing any armor. 

There are some ability in EnderIO armors that you can use, like elytra,nightvision,speed, doube jump... These things works fine, but the armor "itself" doesn't protect at all, when the Sponge Forge is in present.

Removing Sponge Forge --> Everything works fine

**Comment by tyler489** [comment]
Note Absorption is what the armor uses its energy stored not the potion effect

**Comment by batteryhun78** [comment]
![2018-07-19_09 09 50](https://user-images.githubusercontent.com/29629248/42927073-982133e2-8b33-11e8-84fc-3370669670b6.png)

For example. If I'm wearing the boots, the fall damage reducing works, so it takes energy from the boots, so i don'take damage. But when we talk about "protection" like getting hit be arrow/zombie hits, the armor doesn't work

**Comment by ryantheleach** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/b6ef960f0d4f7f8a06516f089107fb79a2a0d0d7/enderio-base/src/main/java/crazypants/enderio/base/item/darksteel/ItemDarkSteelArmor.java#L345 For relevant ender IO code.

**Comment by Zidane** [comment]
Can you retest with the latest SF? I think this was fixed.

**Comment by Kantets** [comment]
The problem still remains relevant on SpongeForge: 1.12.2-2838-7.1.7-RC3896

**Comment by HenryLoenwind** [comment]
I think this should be labeled "type: forge incompatibility", not "type: mod incompatibility". Ender IO isn't doing anything special with the "damage to player" part.

**Comment by gabizou** [comment]
Please don't just close an issue without a response or reason why...



> I think this should be labeled "type: forge incompatibility", not "type: mod incompatibility". Ender IO isn't doing anything special with the "damage to player" part.

We don't have a label for that. In a sense, it's an incompatibility with `forge` as a mod in itself.
