### ISSUE TITLE
Cause Stack Frame Corruption

### ISSUE THREAD

**Issue by Aipaloovik** [SpongePowered/SpongeForge#2330]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3307
- Forge version: forge-1.12.2-14.23.4.2705
- Java version: 1.8
- Operating System: Unbuntu 16.04

- Plugins/Mods: Pixelmon, CustomNPCs, VariedCommodities

**Issue Description**
All of a sudden started getting this error. Not entirely sure where it is coming from. Usually results in a crash

https://gist.github.com/Aipaloovik/9a7324f7d9a7e22787d84b912136e70d

**Comment by Lemmmy** [comment]
Try upgrading to the latest SpongeForge (3328).

**Comment by gabizou** [comment]
Already fixed in a recent commit.

**Comment by Aipaloovik** [comment]
Still getting this issue
Log: https://gist.github.com/Aipaloovik/5171db37aad8dceed85c0a5b84246007
Running: spongeforge-1.12.2-2705-7.1.0-BETA-3334

**Comment by ryantheleach** [comment]
@Aipaloovik Is it constant? Only when your world is loaded? Only when used on a certain modpack?

Is this the full error message? I can't see what originally triggered it easily.

**Comment by XakepSDK** [comment]
@Aipaloovik please, add `-Dsponge.debugcauseframes=true` before `-jar` in your startup cmd line.
e.g. `java -Dsponge.debugcauseframes=true -jar forge.jar`

**Comment by Aipaloovik** [comment]
@ryantheleach 
It happens multiple times before eventually just crashing.
Here is a larger log: https://gist.github.com/Aipaloovik/9a04ef8e39161d181bb5fac326535c9c
There is also a "Completing incorrect phase" error in there, not sure if it's related.
The mods installed are Pixelmon and CustomNPCs.
I have yet to determine anything that causes it in particular. Sometimes it doesn't happen for hours, other times it happens soon after the server starts.

@XakepSDK I'll add that flag for the next reboot and report back if I get anything useful.

**Comment by bloodmc** [comment]
Looks like it may be caused by the husky plugin. Have you tested without this plugin?

**Comment by Aipaloovik** [comment]
The error is happening on a production server and I can't really remove plugins. Also, the error happens so inconsistently that I couldn't try to reproduce it on a test server. I have been running with the debug flag for 8 hours and haven't gotten the error yet.

Also, husky outputs that debug code all the time. Not just when the error occurs.

I'll wait until I get the error again with the debug flag and see if that gives us some more useful output.

**Comment by bloodmc** [comment]
I've seen the husky UI plugin have issues with later SF builds causing it to get stuck in a loop which could easily result in server hanging. When this issue happens, do users have trouble opening their inventory?

**Comment by Aipaloovik** [comment]
As soon as the error starts happening there is usually less than a minute before the server just hangs so I haven't gotten any data on inventory usage.

I might just downgrade Sponge. I only went past the RB because GP needed it. I'll just revert back to the minimum of what it needs. Although I think I'll wait for it to happen once more with the debug on.

**Comment by Aipaloovik** [comment]
With `-Dsponge.debugcauseframes=true`
https://gist.github.com/Aipaloovik/b54d071a281b46db632d4a35cd82be50

**Comment by Aaron1011** [comment]
@Aipaloovik: Try changing `max-block-processing-depth=100` to `max-block-processing-depth=80` in `config/sponge/global.conf`. If you're still getting a `StackOverflowError`, try lowing it a little more.

**Comment by gabizou** [comment]
Try build 3343. I'm not sure how it's possible to reproduce the issue, but the changes should fix it. If not, please comment back with a new log :)

**Comment by Aipaloovik** [comment]
Happened again.
Build: spongeforge-1.12.2-2705-7.1.0-BETA-3344
Log: https://gist.github.com/Aipaloovik/6ced6852dd75ac0b268cdedf14c8ff3c

**Comment by gabizou** [comment]
@Aipaloovik can you try the latest builds, build 3358 would be the current latest build as of this writing, I noticed there was another commit for stack overflow issues on block placement. What exactly is it that is being placed that causes the issue? Do you know?

**Comment by Aipaloovik** [comment]
Happening on 3358
Same log as before ([here it is anyway](https://gist.github.com/Aipaloovik/1c3ea69e6eb67eed2825c5919d526fb7))
I have no idea what is being placed since it happens completely randomly (went a whole day without a crash and then crashed today).

Given that this isn't happening to anyone else I'm led to believe it is a problem with a plugin or mod I am using. Is there anything I can do to find a root cause?

**Comment by phit** [comment]
gonna take this to the newer issue for it, please try latest and report in there https://github.com/SpongePowered/SpongeForge/issues/2368
