### ISSUE TITLE
Incorrect ember energy transfer render on server

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2744]
**I am currently running**

forge-1.12.2-14.23.5.2836-universal
spongeforge-1.12.2-2768-7.1.6-RC3616
EmbersRekindled-1.13-hotfix2

- Plugins/Mods:
![image](https://user-images.githubusercontent.com/38190325/57530589-438e2100-7340-11e9-888b-db929c51c465.png)

**Issue Description**
Once I addressed a developer with a similar problem personally, but I could not find a specific solution. A few months later I tried to solve the problem on my own, but nothing succeeded either.

The principle of the problem is extremely simple - on the server embers energy transfer displayed incorrectly. Video-demo: https://youtu.be/KpLdvfLck50

https://github.com/DaedalusGame/EmbersRekindled/issues/164

**Comment by phit** [comment]
this also happened years ago and was fixed on embers end last time https://github.com/SpongePowered/SpongeForge/issues/1528

**Comment by SSKirillSS** [comment]
But unfortunately it still happens. Also in my other issue I received a response from gabizou: https://github.com/DaedalusGame/EmbersRekindled/issues/164

**Comment by phit** [comment]
not still, again, this was definitely fixed for the longest time

**Comment by SSKirillSS** [comment]
Forgot to add. This applies to all projectiles in Embers (Glimmer Lamp, Cinder Staff, Ancient Golem projectiles, etc...).

**Comment by phit** [comment]
still an issue with spongeforge-1.12.2-2825-7.1.6-RC3732
world download to test with [ember-world.zip](https://github.com/SpongePowered/SpongeForge/files/3238348/ember-world.zip)

**Comment by Zidane** [comment]
Can someone test again on latest SF and report back if this is still an issue?

**Comment by SSKirillSS** [comment]
Still an issue.
spongeforge-1.12.2-2838-7.1.7-RC3902
forge-1.12.2-14.23.5.2838-universal

**Comment by Tangosucka** [comment]
still an issue all the way from 3902 till latest

**Comment by SSKirillSS** [comment]
Still an issue. Tested with SF RC3912:
![image](https://user-images.githubusercontent.com/38190325/64908200-ab48e400-d705-11e9-88f8-3b302ae6fef8.png)

**Comment by SSKirillSS** [comment]
spongeforge-1.12.2-2838-7.1.8-RC3957
EmbersRekindled-1.13-hotfix2
forge-1.12.2-14.23.5.2847-universal

Works fine:
![image](https://user-images.githubusercontent.com/38190325/69465981-da2da700-0d93-11ea-8985-960be5f53c51.png)

**Comment by SSKirillSS** [comment]
After testing elsewhere, it turned out that the problem is still relevant. On spawn (near zero coordinates) everything works well. But beyond it, everything is just like in the screenshot below. 
I don’t know if this is related to the coordinates.
![image](https://user-images.githubusercontent.com/38190325/69491187-99708380-0ea2-11ea-8e09-b2964f737899.png)
