### ISSUE TITLE
Ore Excavator only dropping 1 block.

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2786]
**I am currently running**

- SpongeForge version: 3740
- Forge version: 2831
- Java version: 8
- Operating System:

- Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, PwnFilter, RankUpper, SkyClaims

- Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, LagGoggles, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

**Issue Description**

When breaking blocks with ore excavator, it will only drop a single block instead of them all.
Probably related to this? I tested upto 3734 and it works normally on that version, so something between 3735 and 3740 has caused the 1 block drop only issue.
https://github.com/SpongePowered/SpongeCommon/issues/2259

No console/log errors.

**Comment by JBYoshi** [comment]
What mods/plugins are you using?

**Comment by Yorkforce** [comment]
Updated issue with plugins/mods, basically Sky Factory 4.0.5

I did manage to test upto SF 3734 which seemed to work normally on one server, but on another SF4 server ore excavation wouldn't work at all, just had failure errors in the console along with other issues on the server, so it must have been a very recent change. 
I didn't want to test anything above that as alot of very recent versions seem to have some major issues/reverts

**Comment by Shybella** [comment]
This also occurs with veinminer another ore excavator type mod. 

Version: VeinMiner-1.12-0.38.2.647+b31535a
Sponge: 3743
Forge: 2836

FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Comment by JBYoshi** [comment]
I was able to reproduce this with VeinMiner and Tinkers' Construct, and I think I found the problem. I'm actually finding a couple problems involved; I'm working on fixing all of them.

**Comment by JBYoshi** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/4e0ca424127fb916829d504d901187ecaa685845 and https://github.com/SpongePowered/SpongeCommon/commit/8fdae7b6593748e4f75420ad349550f8cbfebf4c.

**Comment by Shybella** [comment]
Confirmed, with Veinminer.

**Comment by Shybella** [comment]
This still occurs with Ore Excavator

Update: It works just fine outside of a GriefPrevention claim. 

Update: It works after a restart then something causes it to break later on GriefPrevention claims but still works outside claims.

**Comment by NixInTheNight** [comment]
Could someone tell me exactly how to fix this?
I'm having the issue in tandem with ars nouveau and oreexcavation
I know this is an ancient thread but maybe someone can find a solution?
I'm playing a slightly modified version of ATM9, the differences being that I have oreexcavation and ESSENTIAL
I should specify that I'm doing this through curseforge
