### ISSUE TITLE
Tinkers Construct Stuff drops additionally to being placed in the Gravestone.

### ISSUE THREAD

**Issue by TheRealDadbeard** [SpongePowered/SpongeForge#2858]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3830 GriefPreventions seems to have an issue with the newest version Edit: RC3837 seem to be working fine! looking if that bug persists! Edit2: Nope crash when breaking block oof going to 3835, this is the crash https://gist.github.com/TheRealDadbeard/f23531ffee6abe8514c4b7d77f6a805c
- Forge version: 2838
- Java version: 8 211
- Operating System: w10

<!-- Please include ALL mods/plugins you had installed when your issue happened, you can get a 
- Plugins/Mods: https://pastebin.com/yb7vTGJP

**Issue Description**
Upon death Tinkers Construct stuff seem to drop and get put into the GraveStone mod that I have. 

https://gist.github.com/TheRealDadbeard/2e195f0b1459778e38c65c38192ddf0c just took it from latest.log while server was running and that issue happened

**Comment by KorewaLidesu** [comment]
Upload the entite debug log sir.

**Comment by TheRealDadbeard** [comment]
[debug.log](https://github.com/SpongePowered/SpongeForge/files/3357440/debug.log)

**Comment by gabizou** [comment]
Should be fixed in latest.

**Comment by TheRealDadbeard** [comment]
Fixed in 3839 or newer? as it's still happening in 3839

[debug.log](https://github.com/SpongePowered/SpongeForge/files/3359571/debug.log)

**Comment by KorewaLidesu** [comment]
try newest version, if it still that issue, then gabizou forget to commit it :/

**Comment by Zidane** [comment]
Can you retest on the latest SF for us again?

**Comment by gabizou** [comment]
Should've been fixed in https://github.com/SpongePowered/SpongeCommon/commit/93cb034470d67f77dd217124eb9ce91b3bb8ec9a#diff-48de49aaf3b2b5701beb5072c00939dcL174 specifically with the `InventoryPlayerMixin` deletion, some legacy mixin code there that never got updated since transactions were processed etc (at least, it was fixed when I tested it there).

**Comment by TheRealDadbeard** [comment]
I updated to the latest one this morning and will test it in the next few hours.

**Comment by TheRealDadbeard** [comment]
Yeah still dropping on the ground with 1.12.2-2838-7.1.7-RC3878 will try now with 3880

Edit: Still happens, Heads and Galacticraft stuff doesn't go into the gravestone either but this could be the mod itself idk
