### ISSUE TITLE
Empty result in Pit Kiln (TerraFirmaCraft)

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#3035]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.8-RC3963
- Forge version: 1.12.2-14.23.5.2847
- Java version: 8

- Plugins/Mods: TerraFirmaCraft-1.12.2-0.27.7.107

**Issue Description**
I do everything like on a wiki - and as a result I get nothing.
This bug reproduced only with SpongeForge. With Forge-server all good.
[Original issue in TFC git.](https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/664)
Help, please =/

**Comment by yaroslav4167** [comment]
This [line](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/40d0ac3709e8ea0c24a2285060e8bf310b88c164/src/main/java/net/dries007/tfc/objects/te/TEPlacedItem.java#L56)
> TEPlacedItem teNew = Helpers.getTE(world, pos, TEPlacedItem.class);

After burning - returns null

Helpers.getTE:
```
@SuppressWarnings("unchecked")
    public static <T extends TileEntity> T getTE(IBlockAccess world, BlockPos pos, Class<T> aClass)
    {
        TileEntity te = world.getTileEntity(pos);
        if (!aClass.isInstance(te)) return null;
        return (T) te;
    }
```
That’s all I managed to find.

**Comment by clienthax** [comment]
Hmm, ive seen issues like this when the block/TE is replaced during the current phase.
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/40d0ac3709e8ea0c24a2285060e8bf310b88c164/src/main/java/net/dries007/tfc/objects/te/TEPlacedItem.java#L53

Likely the same reason that https://github.com/mekanism/Mekanism/issues/5691 occurs

Likely dupe of https://github.com/SpongePowered/SpongeForge/issues/3001

**Comment by yaroslav4167** [comment]
[This fix](https://github.com/SpongePowered/SpongeCommon/commit/3480230127f27b3df4c2a3e3b5643a14cb25cb4b) again broke pit kiln =(
SpongeForge: 1.12.2-2838-7.1.9-RC3982

On  SpongeForge 1.12.2-2838-7.1.9-RC3981 - pit kiln works normal.

**Comment by bloodmc** [comment]
@yaroslav4167 Should be fixed in 3983

**Comment by yaroslav4167** [comment]
@bloodmc I tested 3983 - the bug still works.
TFC: MC1.12.2-0.28.0.110

**Comment by bloodmc** [comment]
@yaroslav4167 Give exact steps on how to reproduce.

**Comment by yaroslav4167** [comment]
@bloodmc i published steps in [original TFC git](https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/664) to start burning - hold firestarter.
[Video reproduce](https://youtu.be/97Cd2HtRu8Q)
Burning lasts 5-10 minutes. And in the end, all the elements are deleted. Although resources must remain and be cooked.

**Comment by dualspiral** [comment]
Just to complete this cycle, I installed TFC and finally worked out how to do this - and it worked fine on the latest SF (unfired large vessel became a large vessel I could pick up after the pit kiln finished burning - which I set to 20 ticks!) so I'm satisfied that this is resolved.

**Comment by yaroslav4167** [comment]
@dualspiral Try remelting 4 "Unfired Ingot Mold".
My Pit Kiln is very unstable on the latest SF RC3986. Either it melts only one object, or none at all.

**Comment by mem0rz** [comment]
> @dualspiral Try remelting 4 "Unfired Ingot Mold".
> My Pit Kiln is very unstable on the latest SF RC3986. Either it melts only one object, or none at all.

Hello.I have same issue.
Which version is suitable for tfc?

**Comment by yaroslav4167** [comment]
@cybmp3 SF rc3981didn't have this problem. But this version includes problems that do not affect TFC.

**Comment by mem0rz** [comment]
> Just to complete this cycle, I installed TFC and finally worked out how to do this - and it worked fine on the latest SF (unfired large vessel became a large vessel I could pick up after the pit kiln finished burning - which I set to 20 ticks!) so I'm satisfied that this is resolved.

rc3987 still has problem.

**Comment by mem0rz** [comment]
> @cybmp3 SF rc3981didn't have this problem. But this version includes problems that do not affect TFC.

Thank you.

**Comment by LemADEC** [comment]
For the record, a similar issue is reproduced with the pit/kiln from Pyrotech using SpongeForge 1.12.2-2838-7.2.1-RC4010 and pyrotech-1.12.2-1.4.26.
Issue isn't reproduced with SpongeForge 1.12.2-2838-7.1.9-RC3981 and pyrotech-1.12.2-1.4.26.

**Comment by digital-threat** [comment]
Any updates on the issue?
Reproducing it with
SpongeForge-1.12.2-2838-7.3.0
TerraFirmaCraft-1.12.2-1.0.11.140
