### ISSUE TITLE
ICBM-Classic missile lagged with sponge

### ISSUE THREAD

**Issue by Harchvertelol** [SpongePowered/SpongeForge#3136]
**I am currently running**

SpongeForge version: spongeforge-1.12.2-2838-7.2.0
Forge version: 14.23.5.2847
Java version: Java 8
Operating System: Windows 10

- Plugins/Mods:
![image](https://user-images.githubusercontent.com/63555997/79567220-81510900-80bc-11ea-96b9-88e963c4af64.png)
Plugins:
![image](https://user-images.githubusercontent.com/63555997/79567227-86ae5380-80bc-11ea-9f3d-60c515e18f12.png)

ICBM-classic-1.12.2-4.0.1 missile lagged with sponge, problem href:
https://github.com/BuiltBrokenModding/ICBM-Classic/issues/307
and
https://github.com/BuiltBrokenModding/ICBM-Classic/issues/158

What sponge settings do you need to change in order for the mod to work?

**Comment by clienthax** [comment]
I think the last time i looked into icbm most of the issues were fixed on the blast-rewrite.
There were still a few async issues going on for some explosions etc, Would need to look into it again.

Are you running the latest github source compile?

**Comment by Harchvertelol** [comment]
No I am running spongeforge-1.12.2-2838-7.2.0, this is last stable recommended build. I should run latest build 1.12.2-2838-7.2.1-RC4011?

**Comment by Harchvertelol** [comment]
I tested it on the last build (1.12.2-2838-7.2.1-RC4011 from site, not from githab: https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2). The error remained. A similar error occurs when shooting with a miner's laser in the latest version of the industrial craft 2 (version yo can check on screenshot above): the laser beam freezes in the air in a similar way (it twitches) when it flies away from the player (if I fly for a laser, then it flies on, like a rocket in ICBM).

**Comment by clienthax** [comment]
I meant of ICBM not sponge, icbm was basically rewritten lately but i don't believe any jars were released..

**Comment by Harchvertelol** [comment]
No, I using not latest version of ICBM. I using "ICBM - Classic 1.12.2-3.3.0b63 build 63 for 1.12.2". We have "ICBM - Classic 1.12.2-4.0.1b75-UNSTABLE build 75" from 1 april 2020 (but this is not stable!). I can test ICBM of this version with sponge and talk about the results. But, since there is a similar problem in IC2, I do not think that something will change. IC2 I have the latest version.

**Comment by clienthax** [comment]
Yeah generally testing bugs on a build that is over a year old isn't worth anyones time.
I have been running a newer version of icbm classic (from the github) with no issues as such at all.

I am closing this out for now until this is tested on the latest git version.

**Comment by Harchvertelol** [comment]
I tested this with sponge 1.12.2-2838-7.2.0 and sponge 1.12.2-2838-7.2.1-RC4014.
I download latest version "ICBM-Classic 1.12.2-4.0.1b75-UNSTABLE build 75". Lag stayed.

**Comment by Harchvertelol** [comment]
Similarly lag we have with mining laser from latest IC2.

**Comment by Harchvertelol** [comment]
Can you send me your ICBM-Classic jar-file please?

**Comment by clienthax** [comment]
> Can you send me your ICBM-Classic jar-file please?

Not the latest one but this is the one we are using in the pack (name is different to get around curseforge idiocy)
 https://www.curseforge.com/minecraft/mc-mods/i-cant-believe-its-not-icbm/files

If you can reproduce it with that I will send you the latest github compile.

**Comment by Harchvertelol** [comment]
Uploaded
Dec 2, 2019

Old version? Me uisng version from 1 april 2020.

Now I checking this.

**Comment by clienthax** [comment]
Not sure where you got 1/4/2020 from when the version you stated you were using was uploaded on the 19/1/2019 https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/2661985

**Comment by Harchvertelol** [comment]
SpongeVersion: spongeforge-1.12.2-2838-7.2.1-RC4014.jar
ICBM: you file (ICBIN-ICBM-1.12.2-4.0.0.jar)
IC2: industrialcraft-2-2.8.197-ex112.jar

ICBM not working with IC2 energy (insufficient electricity). I not can launch missle.

> I download latest version "ICBM-Classic 1.12.2-4.0.1b75-UNSTABLE build 75". Lag stayed.

I downloaded latest version later and tested it. Lag stayed.

P. S. This version loaded 1 april 2020.

**Comment by Harchvertelol** [comment]
I used early this version: https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/2918052 (1 april 2020) and this version: https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/2915432 (29 March 2020).

Rocket launched (and working with latest IC2), but lagged.

**Comment by clienthax** [comment]
Righty, that explains a lot of the confusion here.
No idea why they have multiple curseforge pages now..

Will take a look

**Comment by Harchvertelol** [comment]
For some reason, the curseforge shows not the latest versions on the main page, you need to click view all.

**Comment by clienthax** [comment]
Make the following changes in the sponge global.conf, and everything will work as expected

```
    entity-activation-range {
        # If 'true', newly discovered entities will be added to this config with a default value.
        auto-populate=true
        # Default activation ranges used for all entities unless overridden.
        defaults {
            ambient=32
            aquatic=32
            creature=32
            misc=16
            monster=32
        }
        # Per-mod overrides. Refer to the minecraft default mod for example.
        mods {
            icbmclassic {
                defaults {
                    misc=16
                }
                # If 'false', entity activation rules for this mod will be ignored and always tick.
                enabled=false
                entities {
                    missile=16
                }
            }
        }
    }
```

**Comment by Harchvertelol** [comment]
Thank you so much, all it's ok!

I have similarly problem with mining laser ("bullet" lagged far away from player, for example Long-Range mode of laser) from latest Industrial craft 2. I should create new issues with this question or I can get help in this topic?

I think that I can set defaults misc 1000 (the laser doesn’t exactly shoot beyond 1000 blocks) and everything will work, but maybe we have other solution, only for IC2? Else we will get bad opimization of server.

**Comment by clienthax** [comment]
> Thank you so much, all it's ok!
> 
> I have similarly problem with mining laser ("bullet" lagged far away from player, for example Long-Range mode of laser) from latest Industrial craft 2. I should create new issues with this question or I can get help in this topic?
> 
> I think that I can set defaults misc 1000 (the laser doesn’t exactly shoot beyond 1000 blocks) and everything will work, but maybe we have other solution, only for IC2? Else we will get bad opimization of server.

You can set the limit per each entity in the mod, enable auto populate and start the server up, it will fill in everything for you and then you can just edit it after

**Comment by Harchvertelol** [comment]
Thank you!

For ic2:

ic2 {
                defaults {
                    misc=16
                }
                # If 'false', entity activation rules for this mod will be ignored and always tick.
                enabled=false
                entities {
                    mininglaser=16
                }
            }
