### ISSUE TITLE
deny-chunk-requests not fully working

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#3188]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.2
- Forge version: forge-1.12.2-14.23.5.2847-universal
- Java version: 1.8

**Issue Description**
The `deny-chunk-requests` doesn't fully work. There are still some tile entities causing the chunks to get loaded without any player or force loaded chunk around it.

This is causing some chunks to be in a load and unload loop. Which can cause frequent lag spikes depending on what's in the chunks. For example AE2 ME Interfaces.

**Comment by dualspiral** [comment]
In 7.2.3, there are two extra optimisations that you can use that might actually be what's going on here. Update, and try enabling the following:

* `disable-raytracing-chunk-loads`
* `disable-pathfinding-chunk-loads`

Let me know if that helps - it might just be that and I can't ask others in the team to look at it until we've ruled these out (or in).

**Comment by Sir-Will** [comment]
Disabled both with version 2838-7.2.4-RC4058 but it didn't change anything.

**Comment by ImMorpheus** [comment]
Enable chunkLoad logging (`chunk-load` in the `logging` category) and post the stacktrace.

**Comment by Sir-Will** [comment]
You are talking about this?
```
[22:49:41] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: SirWill left the game
[22:49:46] [Server thread/INFO] [Sponge]: Load Chunk At [0] (61, 78)
[22:50:17] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:50:17] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:50:17] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:50:17] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:50:20] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:50:20] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3568ms behind, skipping 71 tick(s)
[22:50:48] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:50:48] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:50:48] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:50:48] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:50:51] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3235ms behind, skipping 64 tick(s)
[22:50:51] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:51:19] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:51:19] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:51:19] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:51:19] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:51:23] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3576ms behind, skipping 71 tick(s)
[22:51:23] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:51:51] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:51:51] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:51:51] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:51:51] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:51:54] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3125ms behind, skipping 62 tick(s)
[22:51:54] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:52:22] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:52:22] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:52:22] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:52:22] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:52:25] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3101ms behind, skipping 62 tick(s)
[22:52:25] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:52:53] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:52:53] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:52:53] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:52:53] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:52:56] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3136ms behind, skipping 62 tick(s)
[22:52:56] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:53:24] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:53:24] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:53:24] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:53:24] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:53:27] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3106ms behind, skipping 62 tick(s)
[22:53:27] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:53:55] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:53:55] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:53:55] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:53:55] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:53:58] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3159ms behind, skipping 63 tick(s)
[22:53:58] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:54:26] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:54:26] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:54:26] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:54:27] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:54:30] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3400ms behind, skipping 68 tick(s)
[22:54:30] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:54:58] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:54:58] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:54:58] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:54:58] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:55:01] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3188ms behind, skipping 63 tick(s)
[22:55:01] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:55:29] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:55:29] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:55:29] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:55:29] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:55:32] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3254ms behind, skipping 65 tick(s)
[22:55:32] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:56:00] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:56:00] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:56:00] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:56:00] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:56:04] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3348ms behind, skipping 66 tick(s)
[22:56:04] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
[22:56:32] [Server thread/INFO] [Sponge]: Load Chunk At [0] (69, 91)
[22:56:32] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 90)
[22:56:32] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 88)
[22:56:32] [Server thread/INFO] [Sponge]: Load Chunk At [0] (68, 89)
[22:56:36] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4260ms behind, skipping 85 tick(s)
[22:56:36] [Server thread/INFO] [Sponge]: Load Chunk At [0] (67, 89)
```

**Comment by ImMorpheus** [comment]
Ah sorry, you also need to enable `log-stacktraces`. By default the stacktrace is not logged.

**Comment by Sir-Will** [comment]
https://pastebin.com/raw/pTaQsgMb

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/3087 should help.

Regarding deny-chunk-requests: chunk requests are forced during `TileEntityTickPhase` and can only be denied during certain `PhaseState`s.

**Comment by Sir-Will** [comment]
Thank you! Is there a dev build available I can try out?

**Comment by Sir-Will** [comment]
I just made a build and tested it, the chunks are still getting loaded from neighbor notification with the option enabled.

https://pastebin.com/raw/GQkkNPbF

**Comment by ImMorpheus** [comment]
I missed a spot. Chunks were being loaded while posting `NotifyNeighborBlockEvent`.

Should be fixed now

**Comment by Sir-Will** [comment]
Something seems to be still missing:

https://pastebin.com/raw/uTG9QqHm

**Comment by ImMorpheus** [comment]
> Something seems to be still missing:
> 
> https://pastebin.com/raw/uTG9QqHm

Fixed

**Comment by Sir-Will** [comment]
Unfortunately it's still not fully working but thermal dynamics seems to no longer cause loading.

https://pastebin.com/raw/SjxzgPF6

**Comment by dualspiral** [comment]
I am going to interject here and point out that there is always going to be some chunkloading that we miss - that is the nature of mods. Morph has tracked many of them down but with our 1.14.x development well underway and other bugs that are here on 1.12.2, I, and the rest of the team, really don't want him going back and forth and adding a chunk load denial everywhere. It's just not feasible - he does a lot of good on our 1.12.2 an 1.14.x development and we do need his experience elsewhere!

I admit I thought it'd be two or three places but it's looking like more and more and more, with mods involved most of the time. Realistically, we need to look at what the Phase Tracker is doing and work out why these things are happening in phases we allow - in most cases, probably mods doing things during phases where we'd expect some chunkloading. That's not to say the mods are at fault, many don't write to bypass our phase tracker in such a way!

I'm going to let Morph go as far as he'd like to on this, but please be aware that we just cannot continue to go down this rabbit hole. At some point, he is going to have to push "merge" on that PR. I am going to authorise him to do so at any point he feels it's not worth going further.

If anyone then wants to pick this up and take it further, I'll happily review any PRs that occur.

**Comment by ImMorpheus** [comment]
@Sir-Will See how it goes with the last commit.

Please note that the PR is only about neighbor notification to blocks in unloaded chunks. There are a few stacktrace caused by mods calling (directly or indirectly) `World#getBlockState` and triggering a chunk load. 
There's not much we can do at that point.

Something like:

```
[22:10:13] [Server thread/INFO] [Sponge]: Load Chunk At [0] (58, 87)
[22:10:13] [Server thread/INFO] [Sponge]: Catching
java.lang.Throwable: null
	at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:107) [SpongeHooks.class:1.12.2-2838-7.2.4-RC0]
	at org.spongepowered.common.util.SpongeHooks.logChunkLoad(SpongeHooks.java:219) [SpongeHooks.class:1.12.2-2838-7.2.4-RC0]
	at net.minecraft.world.chunk.Chunk.handler$zmb000$impl$UpdateNeighborsOnLoad(Chunk.java:3555) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:863) [axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.bridge$loadChunkForce(ChunkProviderServer.java:2098) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.redirect$zme000$impl$ProvideChunkForced(ChunkProviderServer.java:1655) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.getChunk(World.java:310) [amu.class:?]
	at net.minecraft.world.World.getChunk(World.java:305) [amu.class:?]
	at net.minecraft.world.WorldServer.getBlockState(WorldServer.java:5077) [oo.class:?]
	at net.minecraft.world.World.isMaterialInBB(World.java:2281) [amu.class:?]
	at micdoodle8.mods.galacticraft.planets.venus.event.EventHandlerVenus.onWorldTick(EventHandlerVenus.java:32) [EventHandlerVenus.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1447_EventHandlerVenus_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
```

is not gonna be fixed by us.
That's galacticraft's event handler triggering a chunk load.

```
	at net.minecraft.world.WorldServer.getBlockState(WorldServer.java:5077) [oo.class:?]
	at net.minecraft.world.World.isMaterialInBB(World.java:2281) [amu.class:?]
	at micdoodle8.mods.galacticraft.planets.venus.event.EventHandlerVenus.onWorldTick(EventHandlerVenus.java:32) [EventHandlerVenus.class:?]
```
https://github.com/micdoodle8/Galacticraft/blob/62a208e201948ec927e6d09ebb5e76e428f77dfc/src/main/java/micdoodle8/mods/galacticraft/planets/venus/event/EventHandlerVenus.java#L32

**Comment by Sir-Will** [comment]
Thank you, looks good now. 👍 

All other chunk loads are "direct" requests like getTileEntity, getBlockState, getChunk... (where I already added a lot of isBlockLoaded/isChunkLoaded checks to mods) which would be more work to implement in sponge.
Might be something for 1.14 with a tile whitelist config,

**Comment by ImMorpheus** [comment]
Thank you for the quick responses and detailed information. They helped a lot.
