### ISSUE TITLE
spongeforge problem with buildcraft quarry

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#543]
When try to build buildcraft quarry, server crashed. Every time when player joined server crashes. Before player join i see in the console:

Server thread/ERROR] [Sponge/]: Entity is not registered EntityMechanicalArm['unknown'/440, l='world', x=130,00, y=63,00, z=940,00]

When player join, server crashes.

When removed SpongeForge, server works without problems.

Sponge crash:

http://pastebin.com/6L2Azd9K

**Comment by Aaron1011** [comment]
Can you reproduce this with the latest SpongeForge?

**Comment by hunter688** [comment]
When place quarry block, see http://pastebin.com/4NXfB7VL in the log now.

Server does not crashed now. I will do some other tests with player who report crash to me.

**Comment by hunter688** [comment]
Hmm server still crashes with latest sponge: http://pastebin.com/6vmzNXAN

**Comment by hunter688** [comment]
Steps to reproduce: place quarry, place creative motor, switch motor on using redstone. Server crashed when quarry is about to start mining, right after it completes its structure.

Without sponge server works as expected.

**Comment by Aaron1011** [comment]
@hunter688: I've confirmed that this is a bug in BuildCraft, and opened an issue: https://github.com/BuildCraft/BuildCraft/issues/3212

**Comment by Aaron1011** [comment]
This issue is now fixed in the latest BuildCraft:

https://github.com/BuildCraft/BuildCraft/issues/3212#issuecomment-189667541

**Comment by hunter688** [comment]
Many thanks!

**Comment by hunter688** [comment]
When compiled new buildcraft, quarry works with sponge now, but in the console still see:  http://pastebin.com/4NXfB7VL May I create another issue?

**Comment by Aaron1011** [comment]
Sure, go ahead!

**Comment by Ceezee** [comment]
I found another issue with the lasted stable version of 1.11.2 sponge forge.
Buildcraft quarry drop items insted of picking them up. this issue in in every quarry if you take that same steps. quarry works fine without sponge on the server
