### ISSUE TITLE
Difficulty mode changes without prompting

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/SpongeForge#568]
I created the main world (New world) and, what I call the farm world, in normal difficulty mode. However, when I start the server, or after I have switched worlds, the main world resets itself to peaceful mode. Locking the mode in normal mode doesn't help either. Any ideas?

http://pastebin.com/embed_iframe/qTmnWJmU

**Comment by Billabonga** [comment]
As a matter of interest, I started a new world in survival mode altogether. It seems that new worlds are set to peaceful mode by default. Is that intentional or just a bug?

**Comment by JBYoshi** [comment]
Possible culprits:
* [`MixinMinecraftServer.loadAllWorlds()` line 451](https://github.com/SpongePowered/SpongeCommon/blob/7b7073ff7ebd45c75b02e296ed4eabb0382265e2/src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java#L451)
* [`MixinMinecraftServer.loadWorld()` line 700](https://github.com/SpongePowered/SpongeCommon/blob/7b7073ff7ebd45c75b02e296ed4eabb0382265e2/src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java#L700)
* [`DimensionManager.initDimension()` line 333](https://github.com/SpongePowered/SpongeCommon/blob/41b03c89d6604a3cb8b6fd7e72edd212d4441d21/src/main/java/org/spongepowered/common/world/DimensionManager.java#L333)

**Comment by gabizou** [comment]
@Zidane I'm assuming that this is fixed for 1.9 update, but what about a 1.8.9 fix?

**Comment by Billabonga** [comment]
Seems to have been fixed ... ?

**Comment by Zidane** [comment]
It isn't fixed.

Basically Vanilla says that whatever difficulty the server has is the one that all worlds has. I'll expose this to the config files and unhook it as part of the "Multi-world commands" PR.

**Comment by Billabonga** [comment]
OK, thanks a lot

**Comment by lantren** [comment]
This is still a thing.  any updates?

**Comment by marshmellion** [comment]
areed this is still a thing and still annoying

**Comment by lantren** [comment]
Yup, ultimately, for me, it means I can't migrate my server to Sponge. too bad.

**Comment by phit** [comment]
Closing this in favor of https://github.com/SpongePowered/SpongeCommon/issues/1165

**Comment by Zidane** [comment]
Just as an update for those on this original issue, I have updated the issue @phit linked above:

SpongePowered/SpongeCommon#1165
