### ISSUE TITLE
Crash on starting sponge with the newest version

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#642]
When I start my server, it crashes with the following crash message. When I try it woth the sponge version 1338 it works but no longer with 1339:

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/274857/fml-server-latest.txt)

**Comment by Zidane** [comment]
Fixed in build 1340.

Apologies again!

**Comment by MrJoki007** [comment]
Not fixed yet 
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/275417/fml-server-latest.txt)

**Comment by Zidane** [comment]
@MrJoki007 

Working fine locally, I'm starting to wonder if there is a cached mixin build happening or something of the sorts.

I'll keep testing, we'll get it figured out

**Comment by Zidane** [comment]
Okay, built a jar of SpongeForge locally and ran it, no problems. Looks like our build site is caching the Mixin jar for whichever reason, we'll look into it.

Here is the pre-built jar from my workspace which is 1:1 master. Can you give it a try?

https://www.dropbox.com/s/5m2o12v3lombe2m/spongeforge-1.8.9-1890-4.1.0-BETA-0.jar?dl=0

**Comment by MrJoki007** [comment]
sure

**Comment by MrJoki007** [comment]
damn

**Comment by MrJoki007** [comment]
The server starts again perfectly but the bug between the worlds is not fixed yet

**Comment by MrJoki007** [comment]
So thats funny again... The enderchest works now between the nether and the normal world but not with the mining world
It all works in singleplayer so it has to be a sponge bug

**Comment by Zidane** [comment]
@MrJoki007 

I don't see how it would be different. The code states that any world who isn't Overworld shares same map storage with Overworld now.

**Comment by Zidane** [comment]
I'll check into it though. Thanks for the testing.

**Comment by MrJoki007** [comment]
I know thats very strange
But im using Aroma1997s Dimensional World (Mining World Mod) 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287828-aroma1997s-mods-betterchests-mining-world-mod
(The world where its bugging out)

**Comment by Zidane** [comment]
@MrJoki007 

Okay I see the issue. I'll be home shortly and fix it at the other spot.

**Comment by MrJoki007** [comment]
Sry for annoying you :(

**Comment by Zidane** [comment]
@MrJoki007 

No annoyance, it is Sponge's fault and mistake and falls on our shoulders to fix. I'm glad you came forward as we would have honestly never found it (until @modwizcode implemented maps I'd imagine ;)).

**Comment by MrJoki007** [comment]
Ok ^^

**Comment by Zidane** [comment]
@MrJoki007 

I've pushed the fix for that dimension. It'll be available in SF 1342 when it builds and uploads. I'll close this again, reopen otherwise.

**Comment by MrJoki007** [comment]
Thanks works perfectly
