### ISSUE TITLE
[1.8.9 URGENT] Massive Duping Issue! 

### ISSUE THREAD

**Issue by IBGnova** [SpongePowered/SpongeForge#965]
Hello,
So recently one of my staff members pointed out a quite concerning issue, this issue is a massive dupe glitch. The way it works:

You need two people.
Place down a chest,
Have one player with the item you want to dupe place the item in the chest's first slot and have them spam one so it will go in and out of their inventory.

The next step is all about random timing, you need the other person to break the chest while the other player is spamming one on the item, and if you time it properly it will dupe the item insane amounts anytime the player with the item opens their inventory. (These items are 100% physical and can be picked up/used).

This is something I find to be quite urgent and needs to be fixed ASAP, if you guys need any help testing this issue please let me know, I would be personally willing to dedicate my time to resolving this issue.

Thanks,
Nova

**Comment by Aaron1011** [comment]
@IBGnova: This sounds like a vanilla bug. Can you see if it can be reproduced on either plain Forge, or Vanilla?

**Comment by IBGnova** [comment]
I tried doing it on a Spigot 1.8.9 server and I could not reproduce it.

**Comment by Aaron1011** [comment]
@IBGnova: It's possible that spigot fixes it. Can you try vanilla and plain forge?

**Comment by IBGnova** [comment]
Sure give me a moment to setup a test server. Would you like the IP, maybe I can show you how it works if it does.

**Comment by IBGnova** [comment]
Ok it's a MC/Forge Issue. I have a test server if you want to see how it works let me know and I will Pm you. I assume if spigot has a fix for this then you guys can make one too?

**Comment by bookerthegeek** [comment]
I know thermos fixes this in 1.7.10, maybe ping them for what exactly causes  this and how they fixed it.

**Comment by IBGnova** [comment]
https://gyazo.com/25634ff556c40f0a54dffd510ab00bff

That is the item that is given to the player when it works. And once they get that they can just keep throwing items out non-stop.

**Comment by Aaron1011** [comment]
@IBGnova: We'll looking into fixing this in Sponge.

**Comment by Aaron1011** [comment]
@IBGnova: Btw, were you able to reproduce this in Vanilla, or only in Forge?

**Comment by IBGnova** [comment]
Will the fix be pushed to 1.8.9 as well?

**Comment by bookerthegeek** [comment]
@Robotia any idea?

**Comment by IBGnova** [comment]
I have been told you guys are mainly focusing on 1.10, but i think this is major enough to make an update for 1.8.9

**Comment by sameer** [comment]
A similar issue was encountered and patched in Thermos. It had to do with negative stack-sizes being returned from mods. I proposed it to be implemented in Forge but the issue I had posted was closed.
Here is the patch that was applied: https://github.com/CyberdyneCC/Thermos/commit/2fd5068cb9a28f5a87d5fba9fc7a6b2cfeec4810

**Comment by inklit** [comment]
This is also possible to do alone with TNT. A player on my server reported it and I mentioned it in IRC however I never got around to opening an issue.
It is a vanilla bug and also works in Forge.

**Comment by ghost** [comment]
Has anyone submitted a bug report to Mojang's JIRA?

**Comment by inklit** [comment]
@octo-byte Considering this issue is fixed in 1.9 and above, I don't think it's necessary to submit this bug to Mojang's JIRA because they likely know about it.
Even if we did I doubt they would backport a fix to 1.8.9.

This needs to be fixed by Forge or Sponge, and Sponge is probably the best place to fix it.

**Comment by IBGnova** [comment]
Any new news on this?

**Comment by Dysthymic** [comment]
This is an issue on latest Sponge 1879 for 1.10 as well. I would consider this as an urgent matter. Every server is effected. 
We tested this without Sponge and it does not occur.

**Comment by bloodmc** [comment]
@IBGnova @Dysthymic @bookerthegeek This was fixed recently in 1.10.2+. Please update to SF 1914+.

https://github.com/SpongePowered/SpongeCommon/commit/2719f2a7fdc4f4cd23c5f3296d5a7ef13be3c0e2

**Comment by bloodmc** [comment]
@IBGnova @Dysthymic @bookerthegeek we will be pushing another fix shortly. 1914 turned out to cause other issues.

**Comment by inklit** [comment]
Glad to hear that @bloodmc! 1914 did not seem to fix it. 
Testing with a different method with a mod transferring items between slots rapidly and clicking, but I believe it's the same bug.

**Comment by inklit** [comment]
Thanks!
